import { builder } from '../builder'
import './booking'
import './cap'
import './competition'
import './contract'
import './fixture'
import './fixtureLeg'
import './goal'
import './injury'
import './loan'
import './match'
import './penaltyShootout'
import './player'
import './playerHistory'
import './squad'
import './squadPlayer'
import './stage'
import './substitution'
import './tableRow'
import './transfer'
import './team'
import { writeFileSync } from 'fs'
import { resolve } from 'path'
import { printSchema } from 'graphql'

export const schema = builder.toSchema({})

writeFileSync(resolve(__dirname, '../../schema.graphql'), printSchema(schema))
